"""empty message

Revision ID: 00002a6265f4
Revises: cacac88087e1
Create Date: 2019-11-18 08:52:41.321547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00002a6265f4'
down_revision = 'cacac88087e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('seeking_description', sa.String(length=250), nullable=True))
    op.add_column('artist', sa.Column('seeking_venue', sa.Boolean(), nullable=True))
    op.add_column('artist', sa.Column('website_link', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'website_link')
    op.drop_column('artist', 'seeking_venue')
    op.drop_column('artist', 'seeking_description')
    # ### end Alembic commands ###
