"""empty message

Revision ID: a8ea06da99f0
Revises: 00002a6265f4
Create Date: 2019-11-18 09:04:41.458264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8ea06da99f0'
down_revision = '00002a6265f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('artist_id', sa.Integer(), nullable=True))
    op.add_column('show', sa.Column('show_date', sa.DateTime(), nullable=True))
    op.add_column('show', sa.Column('venue_id', sa.Integer(), nullable=True))
    op.add_column('venue', sa.Column('seeking_description', sa.String(length=250), nullable=True))
    op.add_column('venue', sa.Column('seeking_venue', sa.Boolean(), nullable=True))
    op.add_column('venue', sa.Column('website_link', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'website_link')
    op.drop_column('venue', 'seeking_venue')
    op.drop_column('venue', 'seeking_description')
    op.drop_column('show', 'venue_id')
    op.drop_column('show', 'show_date')
    op.drop_column('show', 'artist_id')
    # ### end Alembic commands ###
